# Generated by Django 5.0.4 on 2024-04-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalRecojo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('chofer', 'Chofer'), ('ayudante', 'Ayudante')], max_length=8)),
                ('licencia', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('contacto', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
    ]
