# Generated by Django 5.0.6 on 2024-05-08 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_empleados_roles'),
        ('recolecciones', '0002_residuorecolecciones_remove_equiporecojo_personal_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalRecojo',
        ),
        migrations.AddField(
            model_name='empleados',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.roles'),
        ),
    ]
