# Generated by Django 5.0.6 on 2024-05-08 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_delete_personalrecojo_empleados_rol'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='empleados',
            table=None,
        ),
        migrations.AlterModelTable(
            name='roles',
            table=None,
        ),
    ]
