# Generated by Django 5.0.6 on 2024-05-08 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_alter_empleados_table_alter_roles_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='empleados',
            table='personal-empleados',
        ),
        migrations.AlterModelTable(
            name='roles',
            table='personal-roles',
        ),
    ]
