# Generated by Django 5.0.6 on 2024-05-08 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ubicacion',
            name='zona',
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='ciudad',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='provincia',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='region',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='zona_geografica',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='contacto',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
