# Generated by Django 5.0.6 on 2024-05-08 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0003_categorias_ubicaciones_delete_ubicacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorias',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ubicaciones',
            options={},
        ),
    ]
