# Generated by Django 5.0.6 on 2024-05-08 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_empleados_roles'),
        ('recolecciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResiduoRecolecciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField(help_text='Peso en kilogramos')),
            ],
        ),
        migrations.RemoveField(
            model_name='equiporecojo',
            name='personal',
        ),
        migrations.RemoveField(
            model_name='equiporecojo',
            name='recoleccion',
        ),
        migrations.RemoveField(
            model_name='recoleccion',
            name='residuo',
        ),
        migrations.RemoveField(
            model_name='recoleccion',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='recoleccion',
            name='vehiculo',
        ),
        migrations.CreateModel(
            name='Recolecciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateField()),
                ('fecha_realizada', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Progreso', 'En Progreso'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20)),
                ('ayudantes', models.ManyToManyField(blank=True, related_name='recolecciones_como_ayudante', to='personal.empleados')),
                ('conductor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recolecciones_como_conductor', to='personal.empleados')),
            ],
            options={
                'verbose_name_plural': 'recolecciones',
            },
        ),
    ]
