# Generated by Django 5.0.6 on 2024-05-08 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recolecciones', '0002_residuorecolecciones_remove_equiporecojo_personal_and_more'),
        ('residuos', '0002_residuos_tiporesiduos_delete_residuo_residuos_tipo'),
        ('ubicaciones', '0003_categorias_ubicaciones_delete_ubicacion'),
        ('vehiculos', '0002_marcas_modelos_vehiculos_delete_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recolecciones',
            name='ubicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recolecciones', to='ubicaciones.ubicaciones'),
        ),
        migrations.AddField(
            model_name='recolecciones',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recolecciones', to='vehiculos.vehiculos'),
        ),
        migrations.AddField(
            model_name='residuorecolecciones',
            name='recoleccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residuos', to='recolecciones.recolecciones'),
        ),
        migrations.AddField(
            model_name='residuorecolecciones',
            name='residuo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recolecciones', to='residuos.residuos'),
        ),
        migrations.DeleteModel(
            name='EquipoRecojo',
        ),
        migrations.DeleteModel(
            name='Recoleccion',
        ),
    ]
