# Generated by Django 5.0.6 on 2024-05-08 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recolecciones', '0003_recolecciones_ubicacion_recolecciones_vehiculo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recolecciones',
            options={},
        ),
    ]
