# Generated by Django 5.0.6 on 2024-05-08 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recolecciones', '0004_alter_recolecciones_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recolecciones',
            options={'verbose_name_plural': 'recolecciones-recolecciones'},
        ),
        migrations.AlterModelOptions(
            name='residuorecolecciones',
            options={'verbose_name_plural': 'recolecciones-residuorecolecciones'},
        ),
    ]
