# Generated by Django 5.0.6 on 2024-05-08 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recolecciones', '0002_residuorecolecciones_remove_equiporecojo_personal_and_more'),
        ('residuos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residuos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_recoleccion', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'residuos',
            },
        ),
        migrations.CreateModel(
            name='TipoResiduos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Residuo',
        ),
        migrations.AddField(
            model_name='residuos',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residuos', to='residuos.tiporesiduos'),
        ),
    ]
