# Generated by Django 5.0.6 on 2024-05-08 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residuos', '0002_residuos_tiporesiduos_delete_residuo_residuos_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='residuos',
            options={},
        ),
    ]
