# Generated by Django 5.0.6 on 2024-05-08 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residuos', '0003_alter_residuos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='residuos',
            options={'verbose_name_plural': 'residuos-residuos'},
        ),
        migrations.AlterModelOptions(
            name='tiporesiduos',
            options={'verbose_name_plural': 'residuos-tiporesiduos'},
        ),
    ]
