# Generated by Django 5.0.4 on 2024-04-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=255)),
                ('modelo', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('año', models.IntegerField()),
                ('capacidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
    ]
