# Generated by Django 5.0.6 on 2024-05-08 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recolecciones', '0002_residuorecolecciones_remove_equiporecojo_personal_and_more'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'marcas',
            },
        ),
        migrations.CreateModel(
            name='Modelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.marcas')),
            ],
            options={
                'db_table': 'modelos',
            },
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CAMION', 'Camión'), ('FURGONETA', 'Furgoneta'), ('CAMIONETA', 'Camioneta'), ('REMOLQUE', 'Remolque')], max_length=20)),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('capacidad_carga', models.FloatField(help_text='Capacidad en toneladas')),
                ('fecha_adquisicion', models.DateField()),
                ('en_servicio', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.modelos')),
            ],
            options={
                'db_table': 'vehiculos',
            },
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
