# Generated by Django 5.0.6 on 2024-05-08 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_marcas_modelos_vehiculos_delete_vehiculo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='marcas',
            table=None,
        ),
        migrations.AlterModelTable(
            name='modelos',
            table=None,
        ),
        migrations.AlterModelTable(
            name='vehiculos',
            table=None,
        ),
    ]
